# Generated by Django 4.1.3 on 2023-06-13 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='key',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
