# Generated by Django 4.1.3 on 2023-06-16 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_alter_inbox_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='key',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='description',
        ),
    ]
