# Generated by Django 4.1.3 on 2023-04-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='phone_number'),
        ),
    ]
