# Generated by Django 4.1.3 on 2023-04-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_phone_number_newuser_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
