# Generated by Django 4.1.3 on 2023-04-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_newuser_bio_newuser_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
