# Generated by Django 4.1.3 on 2023-04-06 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_ready',
        ),
    ]
