# Generated by Django 4.1.3 on 2023-03-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomePage',
        ),
    ]
