# Generated by Django 4.1.3 on 2023-04-19 18:15

import crypto_wallets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWalletInfo',
            fields=[
                ('crypto_wallet_id', models.CharField(default=crypto_wallets.models.CryptoWalletInfo.generate_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('crypto_balance', models.IntegerField(default=0)),
                ('user_wallet_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
