# Generated by Django 4.1.3 on 2023-04-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowalletinfo',
            name='current_plan',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
