# Generated by Django 4.1.3 on 2023-04-26 17:31

import crypto_wallets.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_wallets', '0002_cryptowalletinfo_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='crypto_wallet_id',
            field=models.CharField(default=crypto_wallets.models.CryptoWalletInfo.generate_id, editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='user_wallet_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
