# Generated by Django 4.1.3 on 2023-04-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0003_alter_cryptowalletinfo_crypto_wallet_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='crypto_balance',
            field=models.FloatField(default=0),
        ),
    ]
