# Generated by Django 4.1.3 on 2023-04-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0004_alter_cryptowalletinfo_crypto_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='current_plan',
            field=models.CharField(max_length=32),
        ),
    ]
