# Generated by Django 4.1.3 on 2023-04-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0005_alter_cryptowalletinfo_current_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='current_plan',
            field=models.CharField(default='None', max_length=32),
        ),
    ]
