# Generated by Django 4.1.3 on 2023-06-17 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_wallets', '0010_alter_cryptowalletinfo_crypto_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptowalletinfo',
            name='crypto_balance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
