# Generated by Django 4.1.3 on 2023-04-07 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountinfo',
            name='bank_account_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccountinfo',
            name='bank_account_number',
            field=models.IntegerField(default=94339, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='bankaccountinfo',
            name='user_bank_acc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
