# Generated by Django 4.1.3 on 2023-04-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_remove_bankaccountinfo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccountinfo',
            name='bank_account_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
