# Generated by Django 4.1.3 on 2023-05-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_market_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmarketexchange',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockmarketexchange',
            name='day',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
