# Generated by Django 4.1.3 on 2023-06-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('product_desc', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('product_title', models.CharField(max_length=50)),
            ],
        ),
    ]
